services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: endpoint do banco de dados
      WORDPRESS_DB_USER: usuario do banco
      WORDPRESS_DB_PASSWORD: senha do banco
      WORDPRESS_DB_NAME: nome do banco
    volumes:
      - /wordpress:/var/www/html
    networks:
      - tunel

networks:
  tunel:
    driver: bridge

